services:
  - type: web
    name: titanic-ml
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 120
    autoDeploy: true
